### PR TITLE
FileUpdate: Add two output properties, "ExitCode" and "NotUpdatedItems". Added logic...

### PR DESCRIPTION
**Pull request by ynauls**
Add two output properties, "ExitCode" and "NotUpdatedItems". Added logic to return a list of items that were NOT updated in the list of files passed into the task.  In addition. it returns ExistCode as true if all files were updated, else false.

### CODE REVIEW

**Comment by aolszowka** [comment]
Hi I had responded to your other thread, but I'm still on vacation (will be for about another week) I did take a quick glance at your code though, I think it looks good. The only concerns I'd have are with the names of the new properties. When I hear "ExitCode" I would expect some numerical value that would tell me if it was successful or not, what about something like "AllItemsUpdated"? and on the files "NotUpdatedItems" what about "ItemsNotUpdated"? Minor changes, and completely optional.

The only other suggestion I might make is to add the ability to include items that failed to update as part of the exception handling statement. It might be nice to know which files did not get modified, however unless something can think of a reason to implement that feature I'd say skip it as well.

I didn't get a chance to build/run those unit tests, but thank you for writing them!

**Comment by piolo108** [comment]
@aolszowka, updated property names based on recommendations.

**Comment by ynauls** [comment]
@aolszowka, what's the road map to push/release this set of changes to nuget?

**Comment by aolszowka** [comment]
Hey its actually @pwelter34 that handles that, I'm just a passionate user, Paul any ETA?

**Pull request merged**
