### PR TITLE
Fix for #219

### PR DESCRIPTION
**Pull request by abdulkareemnalband**
fix invalid executable path for nunit3 task

### CODE REVIEW

**Comment by stevewi1950** [comment]
Hi @abdulkareemnalband.  Don't know if you are aware but you can specify the executable path for the tool as a workaround for this issue.
<NUnit3 Assemblies="@(TestAssemblies)" ToolPath="$(MSBuildProjectDirectory)\lib\NUnit\bin" .../>

We tend to keep the NUnit tool under CM and as such do not use the original installed location for the tool path but supply it above in the msbuild project file as it comes out with our codebase.  I obviously overlooked this when I originally implemented the task (sorry).  Many thanks for the fix, hopefully it will be merged in soon!

Regards.

**Comment by abdulkareemnalband** [comment]
@stevewi1950 thanks for reply,

As i'm new comer to to .net stack let alone msbuild, can you please point me to relevant documentation

**Comment by abdulkareemnalband** [comment]
@stevewi1950 no worries i found documentation at https://msdn.microsoft.com/en-us/library/microsoft.build.utilities.tooltask.toolpath.aspx

**Comment by stevewi1950** [comment]
@abdulkareemnalband pull request #218 updates the documentation for the NUnit3 task which contains an example of it's usage.  I believe all of the MSBuildTasks implement the ability to specify where the executable path is for the tool as it is a part of the base class (ToolTask.cs) along with other standard parameters... https://github.com/Microsoft/msbuild/blob/master/src/Utilities/ToolTask.cs.

As for the parameters to the NUnit3 task are concerned, they pretty much match the NUnit3 documentation hosted here on git hub.

```
<NUnit3 Assemblies="@(TestAssembly)" ToolPath="PathTo nunit-console3.exe" Process="Multiple"  TestTimeout="1000"  Framework="v4.0"  Force32Bit="true"  Workers="1"  EnableShadowCopy="true"  OutputXmlFile="MyTestOutput.xml" WorkingDirectory="./" ShowLabels="All"  InternalTrace="Verbose" NoHeader="true" NoColor="true" 
Verbose="true"/>.

```
Hope this helps.

Regards.

**Comment by abdulkareemnalband** [comment]
@stevewi1950  Thanks a lot

As issue has been resolved i'll close this ticket

**Comment by abdulkareemnalband** [comment]
My bad closed pull request

**Pull request merged**
